'use client'
import {useEffect,useMemo,useState} from 'react'
import {Activity,ArrowRight,BarChart3,Building2,CalendarCheck,Check,Clock3,Download,LayoutDashboard,LogOut,Menu,Plus,Search,ShieldCheck,Sparkles,Users,WalletCards,X} from 'lucide-react'

type Session={id:string;name:string;email:string;role:'ADMIN'|'HR'|'EMPLOYEE';employeeId?:string}
type Employee={id:string;employeeId:string;name:string;email:string;phone?:string;designation:string;salary:number|string;joinedAt:string;status:string;department:{name:string}}
const money=(n:number|string)=>`KSh ${Number(n).toLocaleString('en-KE',{maximumFractionDigits:0})}`
const nav=[['dashboard','Overview',LayoutDashboard],['employees','Employees',Users],['attendance','Attendance',CalendarCheck],['leave','Leave',Clock3],['payroll','Payroll',WalletCards],['performance','Performance',Sparkles],['reports','Reports',BarChart3]] as const

export default function Home(){
 const [session,setSession]=useState<Session|null>(null); const [login,setLogin]=useState({email:'',password:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [page,setPage]=useState('dashboard'); const [open,setOpen]=useState(false); const [employees,setEmployees]=useState<Employee[]>([]); const [data,setData]=useState<any>(null); const [q,setQ]=useState(''); const [showAdd,setShowAdd]=useState(false); const [newEmp,setNewEmp]=useState({name:'',email:'',phone:'',designation:'',salary:'',joinedAt:new Date().toISOString().slice(0,10),departmentId:''}); const [leaves,setLeaves]=useState<any[]>([]); const [payroll,setPayroll]=useState<any[]>([]); const [reviews,setReviews]=useState<any[]>([])
 const load=async()=>{try{const m=await fetch('/api/me');if(!m.ok)throw 0;const mj=await m.json();setSession(mj.session);const [d,e,l,p,r]=await Promise.all([fetch('/api/dashboard'),fetch('/api/employees'),fetch('/api/leave'),fetch('/api/payroll'),fetch('/api/performance')]);setData(await d.json());setEmployees(await e.json());setLeaves(await l.json());setPayroll(await p.json());setReviews(await r.json())}catch{setSession(null)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const filtered=useMemo(()=>employees.filter(e=>[e.name,e.email,e.employeeId,e.department.name].join(' ').toLowerCase().includes(q.toLowerCase())),[employees,q])
 const doLogin=async(e:React.FormEvent)=>{e.preventDefault();setError('');const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(login)});const j=await r.json();if(!r.ok){setError(j.error||'Login failed');return}await load()}
 const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setSession(null)}
 const addEmployee=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch('/api/employees',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...newEmp,salary:Number(newEmp.salary)})});if(r.ok){setShowAdd(false);setNewEmp({name:'',email:'',phone:'',designation:'',salary:'',joinedAt:new Date().toISOString().slice(0,10),departmentId:''});load()}else{const j=await r.json();alert(j.error||'Could not create employee')}}
 if(loading)return <div className="login"><div className="login-art"><div className="logo">E</div><h1>People, payroll & performance — in one place.</h1><p>EmploMS is a modern workforce operating system built for ambitious teams.</p></div></div>
 if(!session)return <div className="login"><section className="login-art"><div className="logo">E</div><h1>Your workforce, intelligently managed.</h1><p>Employees, attendance, leave, payroll and performance in a single premium workspace.</p><div style={{marginTop:30,display:'flex',gap:18,fontSize:11}}><span>✓ Secure RBAC</span><span>✓ PostgreSQL</span><span>✓ Audit-ready</span></div></section><section className="login-panel"><div className="login-card"><div className="logo" style={{color:'#fff'}}>E</div><h2>Welcome back</h2><p>Sign in to your organization workspace.</p>{error&&<div className="error">{error}</div>}<form onSubmit={doLogin}><label>Email<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="admin@company.com"/></label><label>Password<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="••••••••"/></label><button className="primary">Sign in <ArrowRight size={14}/></button></form><p style={{fontSize:9,marginTop:18}}>Use the seeded admin account from your environment setup.</p></div></section></div>
 const title=nav.find(n=>n[0]===page)?.[1]||'Overview'
 return <div className="shell"><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="logo">E</div><div><b>EmploMS</b><small>Workforce OS</small></div></div><div style={{padding:'0 10px 17px',fontSize:9,color:'#6f7b90'}}>ACME WORKSPACE</div><nav className="nav">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={16}/>{label}{id==='leave'&&leaves.filter(x=>x.status==='PENDING').length>0&&<span className="badge">{leaves.filter(x=>x.status==='PENDING').length}</span>}</button>)}</nav><div className="side-bottom"><button onClick={logout}><LogOut size={16}/>Sign out</button><div className="user-mini"><div className="avatar">{session.name.slice(0,2).toUpperCase()}</div><div><b>{session.name}</b><span>{session.role}</span></div></div></div></aside>
 <main className="main"><header className="topbar"><button className="icon mobile-menu" onClick={()=>setOpen(!open)}><Menu size={17}/></button><div><div className="crumb">Workspace / {title}</div><h2>{title}</h2></div><div className="top-actions"><div className="search"><Search size={14}/><input placeholder="Search employees..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="icon"><Activity size={16}/></div><div className="avatar">{session.name.slice(0,2).toUpperCase()}</div></div></header>
 <div className="content">{page==='dashboard'&&<Dashboard data={data} employees={employees} setPage={setPage}/>} {page==='employees'&&<Employees list={filtered} q={q} setQ={setQ} canEdit={session.role!=='EMPLOYEE'} showAdd={()=>setShowAdd(true)}/>} {page==='attendance'&&<Attendance/>}{page==='leave'&&<Leave rows={leaves} role={session.role} reload={load}/>} {page==='payroll'&&<Payroll rows={payroll} employees={employees} role={session.role}/>} {page==='performance'&&<Performance rows={reviews} employees={employees} role={session.role}/>} {page==='reports'&&<Reports data={data} employees={employees} payroll={payroll}/>}</div></main>
 {showAdd&&<div className="modal"><div className="modal-box"><div style={{display:'flex',justifyContent:'space-between'}}><div><h2>Add employee</h2><p>Create a new workforce record.</p></div><button className="icon" onClick={()=>setShowAdd(false)}><X size={16}/></button></div><form className="form" onSubmit={addEmployee}><div className="form-grid"><label>Full name<input required value={newEmp.name} onChange={e=>setNewEmp({...newEmp,name:e.target.value})}/></label><label>Email<input required type="email" value={newEmp.email} onChange={e=>setNewEmp({...newEmp,email:e.target.value})}/></label><label>Designation<input required value={newEmp.designation} onChange={e=>setNewEmp({...newEmp,designation:e.target.value})}/></label><label>Phone<input value={newEmp.phone} onChange={e=>setNewEmp({...newEmp,phone:e.target.value})}/></label><label>Salary (KSh)<input required type="number" value={newEmp.salary} onChange={e=>setNewEmp({...newEmp,salary:e.target.value})}/></label><label>Department<select required value={newEmp.departmentId} onChange={e=>setNewEmp({...newEmp,departmentId:e.target.value})}><option value="">Select department</option>{data?.departments?.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><div className="actions"><button type="button" className="ghost" onClick={()=>setShowAdd(false)}>Cancel</button><button className="primary">Create employee</button></div></form></div></div>}</div>
}
function Dashboard({data,employees,setPage}:{data:any;employees:Employee[];setPage:(x:string)=>void}){return <><div className="hero"><div><span className="eyebrow">WORKFORCE COMMAND CENTER</span><h1>Good morning, team.</h1><p>Here’s the pulse of your organization today.</p></div><div className="actions"><button className="ghost" onClick={()=>setPage('reports')}><Download size={14}/>Reports</button><button className="primary" onClick={()=>setPage('employees')}><Users size={14}/>Manage people</button></div></div><div className="stats"><Stat icon={Users} label="Active employees" value={data?.employees??0} trend="+8.2% this month"/><Stat icon={CalendarCheck} label="Present today" value={data?.present??0} trend="Live attendance"/><Stat icon={Clock3} label="On leave" value={data?.onLeave??0} trend="Current workforce"/><Stat icon={WalletCards} label="Payroll processed" value={money(data?.payroll??0)} trend="Across payroll runs"/></div><div className="grid2"><section className="card panel"><div className="panel-head"><div><h3>Department distribution</h3><span>Active headcount by team</span></div><BarChart3 size={18} color="#6557f5"/></div><div className="bars">{(data?.departments||[]).map((d:any)=>{const max=Math.max(...(data.departments||[]).map((x:any)=>x._count.employees),1);return <div key={d.id}><div className="bar-label"><b>{d.name}</b><span>{d._count.employees} people</span></div><div className="bar"><i style={{width:`${d._count.employees/max*100}%`}}/></div>})}</div></section><section className="card panel"><div className="panel-head"><div><h3>Workforce snapshot</h3><span>Live operational signals</span></div><Sparkles size={18} color="#6557f5"/></div><div className="feed"><Feed text={`${data?.present??0} employees are marked present today`} icon={<Check size={15}/>} /><Feed text={`${data?.onLeave??0} employees are currently on leave`} icon={<Clock3 size={15}/>} /><Feed text={`${employees.length} employee profiles available`} icon={<Users size={15}/>} /><Feed text="Payroll engine is ready for processing" icon={<WalletCards size={15}/>} /></div></section></div></>}
function Stat({icon:Icon,label,value,trend}:{icon:any;label:string;value:any;trend:string}){return <div className="card stat"><div className="stat-top"><div className="stat-icon"><Icon size={17}/></div><span className="trend">● {trend}</span></div><label>{label}</label><strong>{value}</strong></div>}
function Feed({text,icon}:{text:string;icon:any}){return <div className="feed-row"><div className="feed-icon">{icon}</div><div><b>{text}</b><span>Updated just now</span></div></div>}
function Employees({list,q,setQ,canEdit,showAdd}:{list:Employee[];q:string;setQ:(x:string)=>void;canEdit:boolean;showAdd:()=>void}){return <><div className="hero"><div><span className="eyebrow">PEOPLE DIRECTORY</span><h1>Employees</h1><p>Manage profiles, roles, compensation and organizational placement.</p></div>{canEdit&&<button className="primary" onClick={showAdd}><Plus size={15}/>Add employee</button>}</div><div className="toolbar"><input placeholder="Search name, email, ID or department" value={q} onChange={e=>setQ(e.target.value)}/><select><option>All statuses</option><option>Active</option><option>On leave</option></select></div><div className="card table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Department</th><th>Designation</th><th>Joined</th><th>Salary</th><th>Status</th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td><b>{e.name}</b><div style={{color:'#718096',fontSize:8}}>{e.employeeId} · {e.email}</div></td><td>{e.department.name}</td><td>{e.designation}</td><td>{new Date(e.joinedAt).toLocaleDateString('en-KE')}</td><td>{money(e.salary)}</td><td><span className={`status ${e.status==='ACTIVE'?'ok':'warn'}`}>{e.status}</span></td></tr>)}</tbody></table></div></>}
async function Attendance(){const [rows,setRows]=useState<any[]>([]);const [message,setMessage]=useState('');useEffect(()=>{fetch('/api/attendance').then(r=>r.json()).then(setRows)},[]);const check=async()=>{const r=await fetch('/api/attendance',{method:'POST'});setMessage(r.ok?'Checked in successfully.':(await r.json()).error||'Unable to check in');if(r.ok)fetch('/api/attendance').then(x=>x.json()).then(setRows)};return <><div className="hero"><div><span className="eyebrow">TIME & ATTENDANCE</span><h1>Attendance</h1><p>Track daily presence, hours and operational reliability.</p></div><button className="primary" onClick={check}><Clock3 size={15}/>Check in</button></div>{message&&<div className="card panel" style={{marginBottom:15}}>{message}</div>}<div className="card table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Date</th><th>Check in</th><th>Check out</th><th>Hours</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.employee.name}</td><td>{new Date(x.date).toLocaleDateString('en-KE')}</td><td>{x.checkIn?new Date(x.checkIn).toLocaleTimeString('en-KE'): '—'}</td><td>{x.checkOut?new Date(x.checkOut).toLocaleTimeString('en-KE'):'—'}</td><td>{x.hours.toFixed(1)}</td><td><span className="status ok">{x.status}</span></td></tr>)}</tbody></table></div></>}
function Leave({rows,role,reload}:{rows:any[];role:string;reload:()=>void}){const review=async(id:string,status:string)=>{await fetch('/api/leave',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});reload()};return <><div className="hero"><div><span className="eyebrow">TIME OFF WORKFLOW</span><h1>Leave requests</h1><p>Transparent approvals and leave history.</p></div></div><div className="card table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Reason</th><th>Status</th>{role!=='EMPLOYEE'&&<th>Action</th>}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.employee.name}</td><td>{x.type}</td><td>{new Date(x.startDate).toLocaleDateString()} → {new Date(x.endDate).toLocaleDateString()}</td><td>{x.days}</td><td>{x.reason}</td><td><span className={`status ${x.status==='APPROVED'?'ok':x.status==='REJECTED'?'danger':'warn'}`}>{x.status}</span></td>{role!=='EMPLOYEE'&&<td>{x.status==='PENDING'&&<div style={{display:'flex',gap:5}}><button className="primary" style={{padding:'6px 8px'}} onClick={()=>review(x.id,'APPROVED')}><Check size={11}/></button><button className="ghost" style={{padding:'6px 8px'}} onClick={()=>review(x.id,'REJECTED')}>×</button></div>}</td>}</tr>)}</tbody></table></div></>}
function Payroll({rows,employees,role}:{rows:any[];employees:Employee[];role:string}){return <><div className="hero"><div><span className="eyebrow">COMPENSATION</span><h1>Payroll</h1><p>Salary processing, deductions and net pay.</p></div>{role!=='EMPLOYEE'&&<span className="status ok">Payroll engine active</span>}</div><div className="card table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Month</th><th>Basic</th><th>Allowances</th><th>Deductions</th><th>Tax</th><th>Net</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.employee.name}</td><td>{x.month}</td><td>{money(x.basic)}</td><td>{money(x.allowances)}</td><td>{money(x.deductions)}</td><td>{money(x.tax)}</td><td><b>{money(x.net)}</b></td></tr>)}</tbody></table></div></>}
function Performance({rows}:{rows:any[];employees:Employee[];role:string}){return <><div className="hero"><div><span className="eyebrow">GROWTH & PERFORMANCE</span><h1>Performance</h1><p>Reviews, ratings and employee development signals.</p></div></div><div className="grid2">{rows.length?rows.map(x=><div className="card panel" key={x.id}><div className="panel-head"><div><h3>{x.employee.name}</h3><span>{x.period} · reviewed by {x.reviewer}</span></div><span className="status ok">{x.rating}/5</span></div><p>{x.feedback}</p></div>):<div className="card panel"><h3>No reviews yet</h3><p>Create your first performance review from the HR workflow.</p></div>}</div></>}
function Reports({data,employees,payroll}:{data:any;employees:Employee[];payroll:any[]}){const exportCsv=()=>{const rows=[['Employee ID','Name','Department','Designation','Salary'],...employees.map(e=>[e.employeeId,e.name,e.department.name,e.designation,e.salary])];const csv=rows.map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='employees.csv';a.click()};return <><div className="hero"><div><span className="eyebrow">ANALYTICS & REPORTING</span><h1>Reports</h1><p>Turn workforce data into decisions.</p></div><button className="primary" onClick={exportCsv}><Download size={14}/>Export employees CSV</button></div><div className="stats"><Stat icon={Users} label="People" value={employees.length} trend="Directory"/><Stat icon={WalletCards} label="Payroll records" value={payroll.length} trend="Processed"/><Stat icon={Building2} label="Departments" value={data?.departments?.length||0} trend="Organization"/><Stat icon={ShieldCheck} label="Security model" value="RBAC" trend="JWT + roles"/></div><div className="card panel"><div className="panel-head"><div><h3>Department report</h3><span>Headcount distribution</span></div></div>{(data?.departments||[]).map((d:any)=><div key={d.id} style={{display:'flex',justifyContent:'space-between',padding:'13px 0',borderBottom:'1px solid var(--line)',fontSize:11}}><b>{d.name}</b><span>{d._count.employees} employees · {money(d.budget)} budget</span></div>)}</div></>}
